fixed box checkered bg opacity by removing applied class from div
divriots/dockit-core pull request #89
Opened 2022-05-06 12:34 UTC by mveres

This has the disadvantage that the checkered background div ignores other styles such as `border-radius` applied to the box - this might be an isolated corner case.

Another option would be to force `opacity: 1 !important;` and apply the showcase class as well to the checkered bg div.

I'm open to other options as well, I just didn't find a better solution.

2022-05-06 13:05 UTC, bashmish approved these changes

2022-05-06 13:07 UTC, bashmish commented on box/src/Box.module.css
> +  opacity: 1; /* needed to avoid override by showcasing classes and styles*/
despite the comment, I'm not sure I understand it's still needed
I was debugging and saw it worked without it

2022-05-06 13:11 UTC, bashmish requested changes
solution looks good!
but I think `overflow` is buggy and not needed, and `opacity: 1` is not needed

2022-05-09 08:20 UTC, mveres commented
> solution looks good! but I think `overflow` is buggy and not needed, and `opacity: 1` is not needed

I addressed these remarks, so considering it done.
Dismissing the review and merging, because this blocks me from progressing in @dockit-react.

2022-05-09 08:37 UTC, gqio approved these changes

2022-05-09 08:38 UTC, merged